# Generated by Django 4.0.6 on 2022-09-19 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Inventory'},
        ),
    ]
